version: '3.8'

services:
  # --- SERVICIO 1: BASE DE DATOS (MYSQL) ---
  db-mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bddespachosinnovatech
      MYSQL_USER: user_innovatech
      MYSQL_PASSWORD: password_innovatech
    ports:
      - "3306:3306"
    volumes:
      # Montaje para persistir los datos de la BD en la máquina EC2
      - mysql_data:/var/lib/mysql
      # MÁGIA: Copia tu script SQL a la carpeta de inicialización de MySQL en Docker.
      # Se ejecutará automáticamente la primera vez para crear las tablas y cargas.
      - ./innovatech_ev2.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user_innovatech", "-ppassword_innovatech"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- SERVICIO 2: TU BACKEND SPRING BOOT ---
  app-backend:
    image: ${AWS_ACCOUNT_ID}.dkr.ecr.us-east-1.amazonaws.com/backenddespachoinnovatech:latest
    container_name: app-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      # Inyección dinámica de variables mapeadas a tu application.properties
      - DB_HOST=db-mysql
      - DB_PORT=3306
      - DB_NAME=bddespachosinnovatech
      - DB_USER=user_innovatech
      - DB_PASSWORD=password_innovatech
    depends_on:
      db-mysql:
        condition: service_healthy # Espera que MySQL esté 100% listo antes de arrancar el backend

volumes:
  mysql_data: