# Nombre de la aplicacion y puerto
spring.application.name=Springboot-API-REST
server.port=8080

# Configuracion de CORS (Permite que tu frontend acceda al backend)
spring.web.allow-cors=true

# Configuracion de la base de datos MySQL en AWS RDS
# Se incluyen los parametros necesarios para MySQL 8 y AWS
spring.datasource.url=jdbc:mysql://${DB_ENDPOINT}:${DB_PORT}/${DB_NAME}?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=UTF-8
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Configuracion de Hibernate y JPA
spring.jpa.database=mysql
# IMPORTANTISIMO: Desactivamos el script de inicio para que no falle al no encontrar tablas viejas
spring.sql.init.mode=never
# Usamos 'update' para que Spring Boot cree las tablas automáticamente basándose en tus clases @Entity
spring.jpa.hibernate.ddl-auto=update

# Propiedades extra de Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuración de Swagger
springdoc.swagger-ui.path=/swagger-ui.html